title: Centuria Games
description: Official Website of the Hound of Ulster
baseurl: ""
url: https://thecenturiagames.github.io/CenturiaGames/
theme: minima
css:
  - "/assets/css/style.css"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
markdown: kramdown