title: Centuria Games
description: Official Website of the Hound of Ulster
baseurl: "/CenturiaGames"
url: "https://thecenturiagames.github.io"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
markdown: kramdown